### ISSUE TITLE
Add an easy way to enable auto updates

### ISSUE THREAD

**Issue by pklaschka** [fliegwerk/electron-react-boilerplate#6]
Since the GitHub actions workflow already publishes the `latest.yml` files, the only thing missing for auto-updates would be a little bit of code, as far as I understand it.

I believe that this is rather standard functionality and would be great if I could just use it by making a comment a "real" line of code or something like that:

```js
// enableAutoUpdates() // uncomment this to enable auto updates
```

**Comment by fussel178** [comment]
Nice idea!
I will look into it.
